theme = "blowfish"
# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

baseURL = "http://blog-robertorodriguez.surge.sh/"
defaultContentLanguage = "es"

enableRobotsTXT = true
paginate = 20
summaryLength = 30

buildDrafts = false
buildFuture = false
#Â googleAnalytics = "G-XXXXXXXXX"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
[module]
  [[module.imports]]
    path = "cj.rs/gohugo-asciinema"
